### PR TITLE
Fixed Hidden Power Z-move bug

### PR DESCRIPTION
**Pull request by ghost**
I edited the damage.js and move_data.js files so the using the hidden power Z-move no longer returns NaN.

### CODE REVIEW

**Comment by jake-white** [comment]
Thanks, this was on the list and I hadn't gotten around to it. Appreciate it.
Minor edit, I changed it to `return typeChart["Normal"][type];` as HP Z-moves actually retain normal typing and not their individual typing.

**Comment by ghost** [comment]
That line of code was supposed to be for normal usage of hidden power, not the z-move. I think now all hidden powers are normal type.
image

**Comment by jake-white** [comment]
Yep, I'm half asleep. I quickly reverted and made the correct change
`if(move.isZ) return typeChart["Normal"][type];`
`else return typeChart[hpType][type];`

**Comment by jake-white** [comment]
This fix made it so the hidden power typing only changed effectiveness, and Normal type was used for everything else (STAB, weather, abilities, etc).  So, HP Fire was not getting a sun boost, stuff like that. I fixed it by doing the type check in the initial damage calculation.

**Pull request merged**
